baseURL = 'https://satococoa.dev/'
languageCode = 'ja-JP'
title = 'satococoa.dev'
theme = 'PaperMod'
googleAnalytics = 'G-063LZ5YTLV'

[[menu.main]]
identifier = 'archives'
name = 'archives'
url = '/archives/'
weight = 10
[[menu.main]]
identifier = 'search'
name = 'search'
url = '/search/'
weight = 20

[outputs]
home = ['HTML', 'RSS', 'JSON']

[params]
ShowShareButtons = true
ShareButtons = ['twitter', 'facebook']
ShowPostNavLinks = true
ShowBreadCrumbs = true
DateFormat = "2006/01/02 15:04:05"
ShowCodeCopyButtons = true
showtoc = true
TocOpen = true

[params.homeInfoParams]
Title = 'Satoshi Ebisawa (@satococoa)'
Content = '''
Web 系のプログラマです。

Ruby や Go が好き。
2021/06〜2021/12まで育休中。
'''

[[params.socialIcons]]
name = 'twitter'
url = 'https://twitter.com/satococoa'
[[params.socialIcons]]
name = 'github'
url = 'https://github.com/satococoa'
[[params.socialIcons]]
name = 'facebook'
url = 'https://facebook.com/satoshi.ebisawa'
[[params.socialIcons]]
name = 'rss'
url = 'https://satococoa.dev/index.xml'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
